#!/bin/sh

if [ ! $(which fswatch) ]; then
  echo "You need to install fswatch to use watch"
  exit 1
fi

export PATH=node_modules/.bin:$PATH
export LIVERELOAD=true

echo "Initial compile"
make -s

echo "\033[0;34mDone\033[0m"
echo "\033[0;32mWatching...\033[0m"

# Start LiveReload server
tiny-lr &

# Start application with Nodemon for watching
nodemon dist/index.js \
  --watch dist/index.js &

# Watch src and Make on changes
fswatch -0o ./src | while read -d "" event; \
  do \
    make --question
    status=$?

    if [ $status -eq 1 ]; then
      make
    fi
  done
