export const ADD_MESSAGE = 'ADD_MESSAGE';
export const EDIT_MESSAGE = 'EDIT_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const SEND_MESSAGE_STARTED = 'SEND_MESSAGE_STARTED';
export const SEND_MESSAGE_COMPLETED = 'SEND_MESSAGE_COMPLETED';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';
export const LOAD_MESSAGES_STARTED = 'LOAD_MESSAGES_STARTED';
export const LOAD_MESSAGES_COMPLETED = 'LOAD_MESSAGES_COMPLETED';
export const LOAD_MESSAGES_FAILED = 'LOAD_MESSAGES_FAILED';

export const ADD_FLOW = 'ADD_FLOW';
export const REMOVE_FLOW = 'REMOVE_FLOW';
export const ADD_PRIVATE_CONVERSATION = 'ADD_PRIVATE_CONVERSATION';
export const REMOVE_PRIVATE_CONVERSATION = 'REMOVE_PRIVATE_CONVERSATION';

export const LOAD_FLOWS_STARTED = 'LOAD_FLOWS_STARTED';
export const LOAD_FLOWS_COMPLETED = 'LOAD_FLOWS_COMPLETED';
export const LOAD_FLOWS_FAILED = 'LOAD_FLOWS_FAILED';
export const LOAD_PRIVATE_CONVERSATIONS_STARTED = 'LOAD_PRIVATE_CONVERSATIONS_STARTED';
export const LOAD_PRIVATE_CONVERSAFLOWS_COMPLETED = 'LOAD_PRIVATE_CONVERSATIONS_COMPLETED';
export const LOAD_PRIVATE_CONVERSAFLOWS_FAILED = 'LOAD_PRIVATE_CONVERSATIONS_FAILED';

export const SHOW_ROOM = 'SHOW_ROOM';
export const CLOSE_ROOM = 'CLOSE_ROOM';
