export const ADD_MESSAGE = 'ADD_MESSAGE';
export const EDIT_MESSAGE = 'EDIT_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const SEND_MESSAGE_STARTED = 'SEND_MESSAGE_STARTED';
export const SEND_MESSAGE_COMPLETED = 'SEND_MESSAGE_COMPLETED';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';
export const REQUEST_MESSAGES = 'REQUEST_MESSAGES';
export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';
export const FETCH_MESSAGES_FAILED = 'FETCH_MESSAGES_FAILED';

export const ADD_FLOW = 'ADD_FLOW';
export const REMOVE_FLOW = 'REMOVE_FLOW';
export const ADD_PRIVATE_CONVERSATION = 'ADD_PRIVATE_CONVERSATION';
export const REMOVE_PRIVATE_CONVERSATION = 'REMOVE_PRIVATE_CONVERSATION';

export const LOAD_ROOMS_STARTED = 'LOAD_ROOMS_STARTED';
export const LOAD_ROOMS_COMPLETED = 'LOAD_ROOMS_COMPLETED';
export const LOAD_ROOMS_FAILED = 'LOAD_ROOMS_FAILED';
export const LOAD_PRIVATE_CONVERSATIONS_STARTED = 'LOAD_PRIVATE_CONVERSATIONS_STARTED';
export const LOAD_PRIVATE_CONVERSATIONS_COMPLETED = 'LOAD_PRIVATE_CONVERSATIONS_COMPLETED';
export const LOAD_PRIVATE_CONVERSATIONS_FAILED = 'LOAD_PRIVATE_CONVERSATIONS_FAILED';

export const SHOW_ROOM = 'SHOW_ROOM';
export const CLOSE_ROOM = 'CLOSE_ROOM';

export const LOAD_USERS_STARTED = 'LOAD_USERS_STARTED';
export const LOAD_USERS_COMPLETED = 'LOAD_USERS_COMPLETED';
export const LOAD_USERS_FAILED = 'LOAD_USERS_FAILED';

export const FLOWDOCK_STREAM_CONNECTING = 'FLOWDOCK_STREAM_CONNECTING';
export const FLOWDOCK_STREAM_INITIALIZING = 'FLOWDOCK_STREAM_INITIALIZING';
export const FLOWDOCK_STREAM_CONNECTED = 'FLOWDOCK_STREAM_CONNECTED';
export const FLOWDOCK_STREAM_DISCONNECTING = 'FLOWDOCK_STREAM_DISCONNECTING';
export const FLOWDOCK_STREAM_DISCONNECTED = 'FLOWDOCK_STREAM_DISCONNECTED';
export const FLOWDOCK_RECEIVE_STREAM_MESSAGE = 'FLOWDOCK_RECEIVE_STREAM_MESSAGE';
