export const ADD_MESSAGE = 'ADD_MESSAGE';
export const EDIT_MESSAGE = 'EDIT_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const SEND_MESSAGE_STARTED = 'SEND_MESSAGE_STARTED';
export const SEND_MESSAGE_COMPLETED = 'SEND_MESSAGE_COMPLETED';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';

export const ADD_FLOW = 'ADD_FLOW';
export const REMOVE_FLOW = 'REMOVE_FLOW';
export const ADD_PRIVATE_CONVERSATION = 'ADD_PRIVATE_CONVERSATION';
export const REMOVE_PRIVATE_CONVERSATION = 'REMOVE_PRIVATE_CONVERSATION';
